#define SECRET_SSID "Place SSID here"
#define SECRET_PASS "Plase SSID passphase here"
#define SECRET_API "plase Google API URL here"
#define SECRET_AUTH "Plase Google Authorization URL here"
#define SECRET_SHEET "Plase Google Script URL here"
#define SECRET_AUTHUSER "Plase MKR Google username/email address here"
#define SECRET_AUTHPSW "Plase MKR Google user password here"