#define SECRET_SSID "Place SSID here"
#define SECRET_PASS "Place SSID passphase here"
#define SECRET_API "Place Google API URL here"
#define SECRET_AUTH "Place Google Authorization URL here"
#define SECRET_SHEET "Place Google Script URL here"
#define SECRET_AUTHUSER "Place MKR Google username/email address here"
#define SECRET_AUTHPSW "Place MKR Google user password here"